/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OcorrenciasRouteImport } from './routes/ocorrencias'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as ExecutivoRouteImport } from './routes/executivo'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CentralRouteImport } from './routes/central'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OcorrenciasIdRouteImport } from './routes/ocorrencias.$id'

const OcorrenciasRoute = OcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoRoute = ExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasIdRoute = OcorrenciasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OcorrenciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/central': typeof CentralRoute
  '/cliente': typeof ClienteRoute
  '/dispatch': typeof DispatchRoute
  '/equipes': typeof EquipesRoute
  '/executivo': typeof ExecutivoRoute
  '/frota': typeof FrotaRoute
  '/motorista': typeof MotoristaRoute
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/ocorrencias/$id': typeof OcorrenciasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/central': typeof CentralRoute
  '/cliente': typeof ClienteRoute
  '/dispatch': typeof DispatchRoute
  '/equipes': typeof EquipesRoute
  '/executivo': typeof ExecutivoRoute
  '/frota': typeof FrotaRoute
  '/motorista': typeof MotoristaRoute
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/ocorrencias/$id': typeof OcorrenciasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automacoes': typeof AutomacoesRoute
  '/central': typeof CentralRoute
  '/cliente': typeof ClienteRoute
  '/dispatch': typeof DispatchRoute
  '/equipes': typeof EquipesRoute
  '/executivo': typeof ExecutivoRoute
  '/frota': typeof FrotaRoute
  '/motorista': typeof MotoristaRoute
  '/ocorrencias': typeof OcorrenciasRouteWithChildren
  '/ocorrencias/$id': typeof OcorrenciasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automacoes'
    | '/central'
    | '/cliente'
    | '/dispatch'
    | '/equipes'
    | '/executivo'
    | '/frota'
    | '/motorista'
    | '/ocorrencias'
    | '/ocorrencias/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automacoes'
    | '/central'
    | '/cliente'
    | '/dispatch'
    | '/equipes'
    | '/executivo'
    | '/frota'
    | '/motorista'
    | '/ocorrencias'
    | '/ocorrencias/$id'
  id:
    | '__root__'
    | '/'
    | '/automacoes'
    | '/central'
    | '/cliente'
    | '/dispatch'
    | '/equipes'
    | '/executivo'
    | '/frota'
    | '/motorista'
    | '/ocorrencias'
    | '/ocorrencias/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CentralRoute: typeof CentralRoute
  ClienteRoute: typeof ClienteRoute
  DispatchRoute: typeof DispatchRoute
  EquipesRoute: typeof EquipesRoute
  ExecutivoRoute: typeof ExecutivoRoute
  FrotaRoute: typeof FrotaRoute
  MotoristaRoute: typeof MotoristaRoute
  OcorrenciasRoute: typeof OcorrenciasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ocorrencias': {
      id: '/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof OcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo': {
      id: '/executivo'
      path: '/executivo'
      fullPath: '/executivo'
      preLoaderRoute: typeof ExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias/$id': {
      id: '/ocorrencias/$id'
      path: '/$id'
      fullPath: '/ocorrencias/$id'
      preLoaderRoute: typeof OcorrenciasIdRouteImport
      parentRoute: typeof OcorrenciasRoute
    }
  }
}

interface OcorrenciasRouteChildren {
  OcorrenciasIdRoute: typeof OcorrenciasIdRoute
}

const OcorrenciasRouteChildren: OcorrenciasRouteChildren = {
  OcorrenciasIdRoute: OcorrenciasIdRoute,
}

const OcorrenciasRouteWithChildren = OcorrenciasRoute._addFileChildren(
  OcorrenciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomacoesRoute: AutomacoesRoute,
  CentralRoute: CentralRoute,
  ClienteRoute: ClienteRoute,
  DispatchRoute: DispatchRoute,
  EquipesRoute: EquipesRoute,
  ExecutivoRoute: ExecutivoRoute,
  FrotaRoute: FrotaRoute,
  MotoristaRoute: MotoristaRoute,
  OcorrenciasRoute: OcorrenciasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
